// <auto-generated />
using System;
using Berke.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Berke.Data.Migrations
{
    [DbContext(typeof(BerkeContext))]
    partial class BerkeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Berke.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Super Mario Bros.",
                            Overview = "In the fantasy setting of the Mushroom Kingdom, a tribe of turtle-like creatures known as the Koopa Troopas invade the kingdom and uses the magic of its king, Bowser, to turn its inhabitants, known as the Mushroom People, into inanimate objects such as bricks, stones and horsehair plants. Bowser and his army also kidnap Princess Toadstool, the princess of the Mushroom Kingdom and the only one with the ability to reverse Bowser's spell. After hearing the news, Mario sets out to save the princess and free the kingdom from Bowser. After traveling through various parts of the kingdom and fighting Bowser's forces along the way, Mario reaches Bowser's final stronghold, where he is able to defeat him by striking an axe on the bridge suspended over lava he is standing on, breaking the bridge, defeating Bowser, and allowing for the princess to be freed and saving the Mushroom Kingdom.",
                            ReleaseDate = new DateTime(1985, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doom",
                            Overview = "In the future, the player character (an unnamed space marine) has been punitively posted to Mars after assaulting a superior officer, who ordered his unit to fire on civilians. The space marines act as security for the Union Aerospace Corporation's radioactive waste facilities, which are used by the military to perform secret experiments with teleportation by creating gateways between the two moons of Mars, Phobos and Deimos. Three years later, Deimos disappears entirely and something fraggin' evil starts pouring out of the teleporter gateways, killing or possessing all personnel. The Martian marine unit is dispatched to investigate, with the player character left to guard the perimeter with only a pistol while the rest of the group proceeds inside the base and is killed. Being unable to pilot the shuttle off of Phobos by himself, he realizes that the only way to escape is to go inside and fight his way through the complexes of the moon base.",
                            ReleaseDate = new DateTime(1993, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fallout",
                            Overview = "In the mid-21st century, a worldwide conflict is brought on by global petroleum shortage. Several nations enter Resource Wars over the last of non-renewable commodities, namely oil and uranium from 2052 to 2077. China invades Alaska in the winter of 2066, causing the United States to go to war with China and using Canadian resources to supply their war efforts, despite Canadian complaints. Eventually, the United States violently annexes Canada in February 2076 and reclaims Alaska nearly a year later. After years of conflict, on October 23, 2077, a global nuclear war occurs. It is not known who strikes first, but in less than two hours most major cities are destroyed. The effects of the war do not fade for the next hundred years, and as a consequence, human society has collapsed leaving only survivor settlements barely able to eke out a living in the barren wasteland, while a few live through the occurrence in underground fallout shelters known as Vaults. One of these, Vault 13, is the protagonist's home in Southern California, where the game begins in 2161, 84 years after the war. ",
                            ReleaseDate = new DateTime(1997, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Legend of Zelda",
                            Overview = "A small kingdom in the land of Hyrule is engulfed by chaos when an army led by Ganon, the Prince of Darkness, invaded and stole the Triforce of Power, one part of a magical artifact which alone bestows great strength. In an attempt to prevent him from acquiring the Triforce of Wisdom, Princess Zelda splits it into eight fragments and hides them in secret underground dungeons. Before eventually being kidnapped by Ganon, she commands her nursemaid Impa to find someone courageous enough to save the kingdom. While wandering the land, the old woman is surrounded by Ganon's henchmen, when a young boy named Link appears and rescues her. Upon hearing Impa's plea, he resolves to save Zelda and sets out to reassemble the scattered fragments of the Triforce of Wisdom, with which Ganon can then be defeated.",
                            ReleaseDate = new DateTime(1986, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "SimCity",
                            Overview = "The objective of SimCity is to build and design a city, without specific goals to achieve. The player can mark land as being zoned as commercial, industrial, or residential, add buildings, change the tax rate, build a power grid, build transportation systems and take many other actions, to enhance the city. Once able to construct buildings in a particular area, the too-small-to-see residents, known as Sims, may choose to construct and upgrade houses, apartment blocks, light or heavy industrial buildings, commercial buildings, hospitals, churches, and other structures. The Sims make these choices based on such factors as traffic levels, adequate electrical power, crime levels, and proximity to other types of buildings—for example, residential areas next to a power plant will seldom appreciate to the highest grade of housing. The player may face disasters including flooding, tornadoes, fires (often from air disasters or shipwrecks), earthquakes and attacks by monsters. In addition, monsters and tornadoes can trigger train crashes by running into passing trains.",
                            ReleaseDate = new DateTime(1989, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Final Fantasy",
                            Overview = "Final Fantasy takes place in a fantasy world with three large continents. The elemental powers of this world are determined by the state of four crystals, each governing one of the four classical elements: earth, fire, water, and wind. The world of Final Fantasy is inhabited by numerous races, including humans, elves, dwarves, mermaids, dragons, and robots. Most non-human races have only one town in the game, although individuals are sometimes found in human towns or other areas as well. Four hundred years prior to the start of the game, the Lefeinish people, who used the Power of Wind to craft airships and a giant space station (called the Floating Castle in the game), watched their country decline as the Wind crystal went dark. Two hundred years later, violent storms sank a massive shrine that served as the center of an ocean-based civilization, and the Water crystal went dark. The Earth crystal and the Fire crystal followed, plaguing the earth with raging wildfires, and devastating the agricultural town of Melmond as the plains and vegetation decayed. Some time later, the sage Lukahn tells of a prophecy that four Light Warriors will come to save the world in a time of darkness. ",
                            ReleaseDate = new DateTime(1987, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Flight Simulator",
                            Overview = "In Microsoft Flight Simulator (1.0), the player flies a Cessna 182 in one of four US regions: Chicago, Los Angeles, New York City, or Seattle. The starting airport was Meigs Field in Chicago, with a view of the city skyline to the left and Lake Michigan to the right. It would remain the default airport in future versions of Microsoft Flight Simulator, until the real airport was closed. ",
                            ReleaseDate = new DateTime(1982, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Command and Conquer",
                            Overview = "Command & Conquer is set in an alternate timeline, and begins with a meteorite crashing near the river Tiber in Italy in 1995. The meteorite brings with it an alien substance that scientists call Tiberium, named after its impact site, which can absorb and crystallize precious metals from the surrounding soil, but also terraform its surroundings and produce extremely toxic gases and radiation that is fatal to humans and animals. An ancient, cultic secret society called the Brotherhood of Nod, who claims to have foreseen the potentials of this new substance through their self-proclaimed messianic figure known only as Kane, invests in the development of technology to harvest and refine Tiberium crystals, way ahead of the scientific community's own research, and use the resources it gathers to accumulate a rapidly growing army of followers worldwide.",
                            ReleaseDate = new DateTime(1995, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Diablo",
                            Overview = "After eons of war between angels and demons, the ascension of man prompted the three Lords of Hell (including Diablo himself) to seek victory through influence, prompting their exile into the mortal realm. There, they sowed chaos, distrust, and hatred among men until a group of magi, called the Horadrim, trapped them in enchanted crystals called Soulstones. Diablo's soulstone was buried deep in the earth and a monastery was built over the site. Generations passed and the purpose of the monastery was forgotten.A small town named Tristram sprang up next to the monastery's ruins. When King Leoric rebuilt the monastery as a cathedral, Diablo manipulated its archbishop, Lazarus, to destroy his soulstone prison. Diablo subsequently possessed the king, sending out his knights and priests to battle against peaceful kingdoms, and then possessed the king's son,Prince Albrecht, filling the caves and catacombs beneath the cathedral with creatures formed from the young boy's nightmares. ",
                            ReleaseDate = new DateTime(1997, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dark Forces",
                            Overview = "Dark Forces begins with Kyle and Jan being hired by the Alliance to recover the plans to the Death Star, the Empire's space station outfitted with a superlaser capable of destroying an entire planet. The Rebels use the plans to find a weakness in the station, and eventually destroy it. One year later, the Alliance hires the pair again, this time to investigate an assault on one of their bases by a new type of Imperial soldiers. Kyle's investigation unveils the Dark Trooper Project, headed by General Rom Mohc (Jack Angel). His mission to stop the project takes him to the sewers of Anoat City, where he captures Moff Rebus, an Imperial weapons specialist who developed the weapons used by Dark Troopers. Rebus' interrogation leads him to a weapons research facility in the mountains of Fest and the Gromas mines where minerals are extracted for the Dark Troopers. ",
                            ReleaseDate = new DateTime(1995, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Berke.Domain.GameGenres", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GenreId = 5,
                            GameId = 1
                        },
                        new
                        {
                            GenreId = 3,
                            GameId = 2
                        },
                        new
                        {
                            GenreId = 1,
                            GameId = 3
                        },
                        new
                        {
                            GenreId = 2,
                            GameId = 3
                        },
                        new
                        {
                            GenreId = 4,
                            GameId = 4
                        },
                        new
                        {
                            GenreId = 7,
                            GameId = 4
                        },
                        new
                        {
                            GenreId = 6,
                            GameId = 5
                        },
                        new
                        {
                            GenreId = 2,
                            GameId = 6
                        },
                        new
                        {
                            GenreId = 6,
                            GameId = 7
                        },
                        new
                        {
                            GenreId = 1,
                            GameId = 8
                        },
                        new
                        {
                            GenreId = 2,
                            GameId = 9
                        },
                        new
                        {
                            GenreId = 7,
                            GameId = 9
                        },
                        new
                        {
                            GenreId = 3,
                            GameId = 10
                        });
                });

            modelBuilder.Entity("Berke.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roleplaying"
                        },
                        new
                        {
                            Id = 3,
                            Name = "First Person Shooter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Berke.Domain.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maxis"
                        },
                        new
                        {
                            Id = 3,
                            Name = "iD Software"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Squaresoft"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Interplay"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Westwood"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Blizzard"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lucasarts"
                        });
                });

            modelBuilder.Entity("Berke.Domain.PublisherGames", b =>
                {
                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("PublisherId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PublisherGames");

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            GameId = 1
                        },
                        new
                        {
                            PublisherId = 3,
                            GameId = 2
                        },
                        new
                        {
                            PublisherId = 6,
                            GameId = 3
                        },
                        new
                        {
                            PublisherId = 1,
                            GameId = 4
                        },
                        new
                        {
                            PublisherId = 2,
                            GameId = 5
                        },
                        new
                        {
                            PublisherId = 4,
                            GameId = 6
                        },
                        new
                        {
                            PublisherId = 5,
                            GameId = 7
                        },
                        new
                        {
                            PublisherId = 7,
                            GameId = 8
                        },
                        new
                        {
                            PublisherId = 8,
                            GameId = 9
                        },
                        new
                        {
                            PublisherId = 9,
                            GameId = 10
                        });
                });

            modelBuilder.Entity("Berke.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Password = "hedwig",
                            Username = "Harry"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Password = "crookshanks",
                            Username = "Hermione"
                        });
                });

            modelBuilder.Entity("Berke.Domain.UserGames", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserGames");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GameId = 2
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 4
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 6
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 8
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 10
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 1
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 3
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 5
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 7
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 9
                        });
                });

            modelBuilder.Entity("Berke.Domain.GameGenres", b =>
                {
                    b.HasOne("Berke.Domain.Game", null)
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Berke.Domain.Genre", null)
                        .WithMany("GamesInGenre")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Berke.Domain.PublisherGames", b =>
                {
                    b.HasOne("Berke.Domain.Game", null)
                        .WithMany("Publishers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Berke.Domain.Publisher", null)
                        .WithMany("GamesPublished")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Berke.Domain.UserGames", b =>
                {
                    b.HasOne("Berke.Domain.Game", null)
                        .WithMany("UsersOwning")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Berke.Domain.User", null)
                        .WithMany("GamesOwned")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Berke.Domain.Game", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Publishers");

                    b.Navigation("UsersOwning");
                });

            modelBuilder.Entity("Berke.Domain.Genre", b =>
                {
                    b.Navigation("GamesInGenre");
                });

            modelBuilder.Entity("Berke.Domain.Publisher", b =>
                {
                    b.Navigation("GamesPublished");
                });

            modelBuilder.Entity("Berke.Domain.User", b =>
                {
                    b.Navigation("GamesOwned");
                });
#pragma warning restore 612, 618
        }
    }
}
